# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('idade', models.SmallIntegerField()),
                ('telefone', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['apelido'],
            },
        ),
    ]
